version: '3.7'
services:
  traefik:
    image: "traefik:v2.9"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  javaee_clustered_app:
    image: javaee-clustered-app
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.javaee_clustered_app.entrypoints=web"
      - "traefik.http.routers.javaee_clustered_app.rule=PathPrefix(`/JavaEEClusterApp`)"  
      - "traefik.http.services.javaee_clustered_app.loadbalancer.server.port=8080"
